---
apiVersion: v1
kind: Pod
metadata:
  name: iscsipd
spec:
  containers:
  - name: iscsipd-rw
    image: busybox
    tty: true
    volumeMounts:
    - mountPath: "/var/lib/mysql"
      name: iscsipd-rw
  volumes:
  - name: iscsipd-rw
    iscsi:
      targetPortal: 10.0.0.30:3260
      iqn: iqn.2009-02.com.younglogic:for.all
      lun: 1
      fsType: ext4
      readOnly: false
