---
apiVersion: v1
kind: Pod
metadata:
  name: keystone-config
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: munchlax:5000/keystone-config
      name: keystone-config
      env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: yourpassword
      ports:
        - containerPort: 3306
          name: mysql
