---

- hosts: all
  remote_user: ansible
  sudo: yes
  tasks:
  - setup:


- hosts: all
  remote_user: ansible
  sudo: yes
  tasks:
  - name: nodes to /etc/hosts on all machines
    lineinfile:
      dest: /etc/hosts
      line: >-
        {{ hostvars[item].ansible_default_ipv4.address }}
        {{ item }} {{ item }}.home.younglogic.net
    with_items: "{{ groups.all }}"



