---

# Ansiblization of the instructions from
# https://fedoraproject.org/wiki/Scsi-target-utils_Quickstart_Guide

- name: install iscsi-initiator-utils
  package: name=iscsi-initiator-utils state=latest

- name: ensure the iSCSI service is started 
  service:
    name: iscsi 
    enabled: yes
    state: started

- name: run iscsi_discovery
  command: iscsiadm -m discovery -t  sendtargets  -p {{ iscsi_server }}
  register: iscsi_volumes

- name: login to iSCSI Target
  command: iscsiadm --mode node --targetname {{ iscsi_target }} --portal {{ iscsi_portal }} --login

- name:  set node.startup to manual.
  command: iscsiadm --mode node --targetname {{ iscsi_target }} --portal {{ iscsi_portal }} -o update -n node.startup -v manual


- name: read partition table
  command: fdisk -l  /dev/sdb
  register: sdb_partition_table

- name: copy partition file
  copy: 
    src: sdb.disk
    dest: /tmp/sdb.disk
  when: "'/dev/sdb1' not in  sdb_partition_table.stdout"

- name: create sdb1 partition
  shell: sfdisk /dev/sdb < /tmp/sdb.disk
  when: "'/dev/sdb1' not in  sdb_partition_table.stdout"

# TODO confirm this initializes /dev/sdb1 post creation on a different node
- name:  ensure system sees updated /dev/sdb1
  command: iscsiadm -m session --rescan

- name: fetch files system information
  shell: blkid /dev/sdb1
  register: sdb1_blkid

- name: create file system
  command: mkfs.ext4 /dev/sdb1
  when: "'TYPE' not in sdb1_blkid.stdout"
