---
- name: ensure kubernetes  is at the latest version
  package: name=kubernetes-node state=latest

- name: Make sure we can manage SELinux changes for lineinfile
  package: name=libselinux-python state=latest
   
# The next two targets work together to ensure that the /etc/hosts file has
# an entry for all hosts in the cluster

- name: gather facts from all servers
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"

- name: Add master and node to /etc/hosts on all machines
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }}"
    line: >-
        {{ hostvars[item].ansible_default_ipv4.address }}
        {{ item }} {{ item }}.home.younglogic.net
  with_items: "{{ groups.all }}"


- firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 4194
  - 10250
  - 10255


- name: configure kubelete addrees
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: "^KUBELET_ADDRESS="
    line: KUBELET_ADDRESS="--address=0.0.0.0"
    state: present
  register: kubeletaddr

- name: configure kubelete hostname
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: "^KUBELET_HOSTNAME="  
    line: KUBELET_HOSTNAME="--hostname-override={{ inventory_hostname }}"
    state: present
  register: kubelethostname


- name: configure kubelete hostname
  lineinfile:
    dest: /etc/kubernetes/kubelet
    regexp: "^KUBELET_API_SERVER="  
    line: KUBELET_API_SERVER="--api-servers=http://munchlax:8080"
    state: present
  register: kubeleapi


- name: restart the node services if required
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - kube-proxy
    - kubelet
    - docker
  when: kubeletaddr.changed or  kubelethostname.changed or  kubeleapi.changed


- name: start the node services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - kube-proxy
    - kubelet
    - docker
