---

- name: Make sure we can manage SELinux changes for lineinfile
  package: name=libselinux-python state=latest

- name: add the repo that provides kubeadm
  copy:
    src: cloud.google.com.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: ensure rpms are at the latest version
  package: name={{ item }} state=latest
  with_items:
  - docker
  - python-firewall
  - kubeadm
  - kubectl
  - kubelet

- firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 4194
  - 10250
  - 10255


- name: configure docker to allow insecure registry access
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: "^INSECURE_REGISTRY="  
    line: INSECURE_REGISTRY='--insecure-registry  munchlax:5000'
    state: present
  register: dockerinsecure

- name: restart the node services if required
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - docker
  when:  dockerinsecure.changed


- name: start the node services if required
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - kubelet
    - docker

- name: enroll a kubernetes node
  command: kubeadm join --token=abcdef.1234567890123456 10.0.0.30
