---

# Ansibilzation of the instructions
# https://fedoraproject.org/wiki/Scsi-target-utils_Quickstart_Guide


- name: install scsi-target-utils
  package: name=scsi-target-utils state=latest


- name: configure firewall
  firewalld:
    service: iscsi-target
    permanent: true
    state: enabled

- stat:
    path: /var/tmp/iscsi-disk1
  register: scsistorage

- name: allocate storage
  command: dd if=/dev/zero of=/var/tmp/iscsi-disk1 bs=1M count=8000
  when: scsistorage.stat.islnk is not defined

- name: set SELlinux context
  command: semanage fcontext -a -t tgtd_var_lib_t /var/tmp/iscsi-disk1
  when: scsistorage.stat.islnk is not defined

- name: restore SELlinux context
  command: restorecon -Rv  /var/tmp/iscsi-disk1
  when: scsistorage.stat.islnk is not defined

- name: ensure the tgtd service is started 
  service:
    name: tgtd
    enabled: yes
    state: started

- name: register active targets
  command:  tgtadm --lld iscsi --mode target --op show
  register: iscsitargets

#TODO change initiator name to a variable
- name: create target device
  command: tgtadm --lld iscsi --mode target --op new --tid=1 --targetname iqn.2009-02.com.younglogic:for.all 
  when:  "'iqn.2009-02.com.younglogic:for.all' not in iscsitargets.stdout"


- name: add a logical unit
  command: tgtadm --lld iscsi --mode logicalunit --op new --tid 1 --lun 1 -b /var/tmp/iscsi-disk1
  when:  "'LUN: 1' not in iscsitargets.stdout"


#TODO make this more targetted to the registered nodes
- name: Restrict access to the local subnet
  command: tgtadm --lld iscsi --mode target --op bind --tid 1 -I 10.10.0.0/24
  when:  "'10.10.0.0/24' not in iscsitargets.stdout"