---

# Ansiblization of the instructions from
# https://kubernetes.io/docs/user-guide/persistent-volumes/
# applied to iSCSI

- name: create kubernetes entities
  sudo: False
  local_action: kubernetes insecure=yes api_endpoint=munchlax:8080 file_reference={{ role_path }}/files/{{ item }}.yaml state=present
  with_items:
     - openstack-namespace
     - keystonedb-pv
     - keystonedb-claim
     - keystonedb-service
     - keystonedb-pod
