---
# Ansibilization of master side of
# https://kubernetes.io/docs/getting-started-guides/fedora/fedora_manual_config/


-  command: sysctl -w net.bridge.bridge-nf-call-iptables=1
-  command: sysctl -w net.bridge.bridge-nf-call-ip6tables=1

- name: disable SELinux for now
  selinux:
    policy: targeted
    state: permissive



- name: add the repo that provides kubeadm
  copy:
    src: cloud.google.com.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: ensure rpms are at the latest version
  package: name={{ item }} state=latest
  with_items:
  - python-firewall
  - kubeadm
  - kubectl
  - kubelet


- name: ensure the required services were started
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
    - kubelet


- firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  with_items:
  - 6443
  - 53
  - 5000
  - 3306
  - 6443
  - 9898
  - 10250


- name: check if Kuberenets is running
  command: kubectl api-versions
  register: kubeapi_status
  ignore_errors: yes

- name: setup Kuberenetes
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --token abcdef.1234567890123456 --use-kubernetes-version v1.4.5 --api-external-dns-names munchlax.home.younglogic.net
  when: kubeapi_status|failed

- name: install weave for networking
  command: kubectl apply -f https://git.io/weave-kube

- name: Allow scheduling pods on master
  command: kubectl taint nodes --all dedicated- 
  ignore_errors: yes


- name: copy admin credentials to local machine
  fetch:
    src:  /etc/kubernetes/admin.conf
    dest: /tmp/
