kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keystonedb
  namespace: openstack
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: "keystonedb"
